### PR TITLE
Lab1

### PR DESCRIPTION
**Pull request by Edward-Saf**

### CODE REVIEW

**Comment by Futurer** [comment]
Generation doesn't work correctly. Try to put this lib http://ftp.gnu.org/gnu/libc/glibc-ports-2.11.tar.gz
as the input data and check the results in differnt modes. 

I used python3 in the comand line.

**Comment by Edward-Saf** [comment]
I have corrected the errors.

Please have a look.

**Comment by Futurer** [comment]
Functions bodies are absent in the documentation pages. The alphabet index is implemented incorrectly. The navigation is not available on the all pages.
Check email for remarks and testing results.

**Comment by Edward-Saf** [comment]
Breadcrumbs are now available on all pages of documentation.
Bugs have been fixed too.

**Pull request merged**
