### PR TITLE
Lab2

### PR DESCRIPTION
**Pull request by Edward-Saf**

### CODE REVIEW

**Comment by Futurer** [comment]
user@pc:~/Downloads/Metaprogramming-lab2/Lab 2$ python3 runformatter.py /home/user/Downloads/Metaprogramming-lab2/tokenize.py 
Traceback (most recent call last):
  File "runformatter.py", line 25, in <module>
    formatter(sys.argv)
  File "/home/user/Downloads/Metaprogramming-lab2/Lab 2/formatter.py", line 50, in formatter
    tokens, indent_levels = tokenize(input_data, config, errors_and_warnings)
  File "/home/user/Downloads/Metaprogramming-lab2/Lab 2/tokenize.py", line 67, in tokenize
    y = dat.index(item)
ValueError: '"' is not in list
user@pc:~/Downloads/Metaprogramming-lab2/Lab 2

Check  the email for testing results.

**Comment by Futurer** [comment]
If you use additional libraries as jinja2, you should create a file with requirements.

**Comment by Edward-Saf** [comment]
I have checked testing results and fixed bugs.

**Comment by Futurer** [comment]
File refact.py from your project

"
def refact(input_data, tokens, config, preformat_messages):
      item_ind = 0
"
wrong indent in second line.

user@pc:~/Downloads/Metaprogramming-lab2/Lab 2$ python3 main.py -f /home/user/Downloads/refact___.py 
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    code_formatter(sys.argv[2])
  File "/home/user/Downloads/Metaprogramming-lab2/Lab 2/code_formatter.py", line 18, in code_formatter
    input_data = tree_parse(input_data, config, preformat_messages)
  File "/home/chester/Downloads/Metaprogramming-lab2/Lab 2/tree_parse.py", line 8, in tree_parse
    tree = parse(data_str)
  File "/home/chester/Downloads/Metaprogramming-lab2/Lab 2/syntax_tree.py", line 18, in parse
    result = drv.parse_string(code, True)
  File "/usr/lib/python3.7/lib2to3/pgen2/driver.py", line 104, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.7/lib2to3/pgen2/driver.py", line 48, in parse_tokens
    for quintuple in tokens:
  File "/usr/lib/python3.7/lib2to3/pgen2/tokenize.py", line 426, in generate_tokens
    ("<tokenize>", lnum, pos, line))
  File "<tokenize>", line 10
    data = []
    ^
IndentationError: unindent does not match any outer indentation level

**Comment by Edward-Saf** [comment]
Removed unwanted stack trace. Please check it again.

**Pull request merged**
